### Application Root
GET http://localhost:3001


### Get List
GET http://localhost:3001/api/currency


### Get record
GET http://localhost:3001/api/currency/1

### Get record not found
GET http://localhost:3001/api/currency/3


### Not Found URL
GET http://localhost:3001/api/not-found-url



### Post Currency - Validation check
POST http://localhost:3001/api/currency
Content-Type: application/json

{
}

### Post Currency
POST http://localhost:3001/api/currency
Content-Type: application/json

{
    "currencyCode": "BRL",
    "conversionRate": 0.9,
    "countryId": 1
}

### PUT Currency
PUT http://localhost:3001/api/currency/2/0.9876


### DELETE Currency
DELETE http://localhost:3001/api/currency/2

