### Application Root
GET http://localhost:3001


### Get List
GET http://localhost:3001/api/country


### Get record
GET http://localhost:3001/api/country/2

### Get record not found
GET http://localhost:3001/api/country/9


### Post country - Validation check
POST http://localhost:3001/api/country
Content-Type: application/json

{
}

### Post country
POST http://localhost:3001/api/country
Content-Type: application/json

{
    "name": "USA"
}

### PUT country
PUT http://localhost:3001/api/country/2/ABCD


### DELETE country
DELETE http://localhost:3001/api/country/2

