name: Pipeline Server

on:
  push:
    branches:
      - main
      - develop
      - production
      - project-part-5

jobs:
  pipeline_test_server:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm install

      - name: Check Lint
        run: npm run lint

      - name: Run test
        run: npm run test
        with:
          SERVER_PORT: 3001
          NODE_ENV: test
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
